django_basics/clinicals/clinicals/urls.py
from django.contrib import admin
from django.urls import path, include
from clinicals_app.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('patients/', include('clinicals_app.urls', namespace='patients')),
]

django_basics/clinicals/clinicals_app/urls.py
from django.urls import path

from clinicals_app.views import PatientCreateView, PatientListView, PatientUpdateView, \
    PatientDeleteView, analyze, add_data

app_name = 'patients'

urlpatterns = [
    path('create/', PatientCreateView.as_view(), name='create'),
    path('list/', PatientListView.as_view(), name='list'),
    path('update/<int:pk>', PatientUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', PatientDeleteView.as_view(), name='delete'),
    path('analyze/<int:pk>', analyze, name='analyze'),
    path('add_data/<int:pk>', add_data, name='add_data'),
]

django_basics/clinicals/clinicals_app/models.py
from django.db import models


class Patient(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField()


class ClinicalData(models.Model):
    HEIGHT_WEIGHT = 'height / weight'
    BLOOD_PRESSURE = 'blood pressure'
    HEART_RATE = 'heart rate'

    COMPONENT_NAMES = [('hw', HEIGHT_WEIGHT), ('bp', BLOOD_PRESSURE), ('hr', HEART_RATE)]

    name = models.CharField(max_length=2, choices=COMPONENT_NAMES)
    value = models.CharField(max_length=20)
    measured_time = models.DateTimeField(auto_now_add=True)
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)

django_basics/clinicals/clinicals_app/forms.py
from django import forms

from clinicals_app.models import Patient, ClinicalData


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = '__all__'


class ClinicalDataForm(forms.ModelForm):
    class Meta:
        model = ClinicalData
        fields = '__all__'

django_basics/clinicals/clinicals_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator

from clinicals_app.forms import ClinicalDataForm, PatientForm
from clinicals_app.models import Patient, ClinicalData


def index(request):
    context = {
        'title': 'Clinicals'
    }
    return render(request, 'index.html', context)


@method_decorator(user_passes_test(lambda u: u.is_authenticated and u.is_staff), name='dispatch')
class PatientCreateView(CreateView):
    model = Patient
    success_url = reverse_lazy('patients:list')
    fields = ('first_name', 'last_name', 'age')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create patient'
        return context


@method_decorator(user_passes_test(lambda u: u.is_authenticated), name='dispatch')
class PatientListView(ListView):
    model = Patient

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'List patients'
        return context


@method_decorator(user_passes_test(lambda u: u.is_authenticated and u.is_staff), name='dispatch')
class PatientUpdateView(UpdateView):
    model = Patient
    fields = ('first_name', 'last_name', 'age')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update patient'
        return context

    def post(self, request, *args, **kwargs):
        patient = self.get_object()
        form = PatientForm(data=self.request.POST, instance=patient)

        if form.is_valid():
            form.save()
            messages.success(self.request, 'Success! Patient data was updated!')
            return redirect(self.request.META['HTTP_REFERER'])
        else:
            messages.error(self.request, 'recheck fields')
            return redirect(self.request.META['HTTP_REFERER'])


@method_decorator(user_passes_test(lambda u: u.is_authenticated and u.is_superuser),
                  name='dispatch')
class PatientDeleteView(DeleteView):
    model = Patient
    success_url = reverse_lazy('patients:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Delete patient'
        return context


@login_required
def add_data(request, pk):
    patient = Patient.objects.get(pk=pk)
    clinical_data = ClinicalData(patient=patient)
    clinical_data_form = ClinicalDataForm(instance=clinical_data)
    if request.method == 'POST':
        clinical_data_form = ClinicalDataForm(data=request.POST)
        clinical_data_form.save()
        return redirect('patients:list')

    context = {
        'title': 'Add data',
        'patient': patient,
        'clinical_data_form': clinical_data_form,
    }
    return render(request, 'clinicals_app/patient_add_data.html', context)


@login_required
def analyze(request, pk):
    patient = Patient.objects.get(pk=pk)
    clinical_data = ClinicalData.objects.filter(patient=patient)

    hr_measured = clinical_data.filter(name='hr')
    last_hr = clinical_data.filter(name='hr').order_by(
        '-measured_time').first().value if hr_measured else 'Not measured yet'

    hw_measured = clinical_data.filter(name='hw')
    last_hw = clinical_data.filter(name='hw').order_by(
        '-measured_time').first().value if hw_measured else 'Not measured yet'

    bp_measured = clinical_data.filter(name='bp')
    last_bp = clinical_data.filter(name='bp').order_by(
        '-measured_time').first().value if bp_measured else 'Not measured yet'

    context = {
        'title': 'Patient analyze',
        'patient': patient,
        'clinical_data': clinical_data,
        'last_hr': last_hr,
        'last_hw': last_hw,
        'last_bp': last_bp,
    }
    return render(request, 'clinicals_app/patient_analyze.html', context)

django_basics/clinicals/templates/clinicals_app/patient_add_data.html
{% extends 'base.html' %}

{% block title %}
    <title> {{ title | title }}</title>
{% endblock %}

{% block content %}

    First Name: {{ patient.first_name }}<br>
    Last Name: {{ patient.last_name }}<br>
    Age: {{ patient.age }}<br>

    <form method="post">
        {% csrf_token %}
        {{ clinical_data_form.as_p }}
        <input type="submit" value="Add">
    </form>

    <a class="btn btn-success" href="{% url 'patients:list' %}">Back to Patients list</a>

{% endblock %}

django_basics/clinicals/templates/clinicals_app/patient_analyze.html
{% extends 'base.html' %}

{% block title %}
    <title> {{ title | title }}</title>
{% endblock %}

{% block content %}

    First Name: {{ patient.first_name }}<br>
    Last Name: {{ patient.last_name }}<br>
    Age: {{ patient.age }}<br>
    Last heart rate: {{ last_hr }}<br>
    Last height / weight: {{ last_hw }}<br>
    Last blood preassure: {{ last_bp }}<br>

    {% include 'clinicals_app/includes/inc_data_table.html' %}

    <a class="btn btn-success" href="{% url 'patients:add_data' patient.pk %}">Add Data</a>
    <a class="btn btn-success" href="{% url 'patients:list' %}">Back to Patients list</a>
{% endblock %}

django_basics/clinicals/templates/clinicals_app/patient_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
<title> {{ title | title }}</title>
{% endblock %}

{% block content %}

    <form method="post">
    {% csrf_token %}
    <h1>Delete {{ patient.first_name}} {{ patient.last_name}} ?</h1>
        <input class="btn btn-danger" type="submit" value="OK">
        <a href="{% url 'patients:list' %}">Cancel</a>
    </form>

{% endblock %}

django_basics/clinicals/templates/clinicals_app/patient_form.html
{% extends 'base.html' %}

{% block title %}
    <title> {{ title | title }}</title>
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

    <a class="btn btn-success" href="{% url 'patients:list' %}">Back to Patients list</a>

{% endblock %}

django_basics/clinicals/templates/clinicals_app/patient_list.html
{% extends 'base.html' %}

{% block title %}
    <title> {{ title | title }}</title>
{% endblock %}

{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Age</th>
            <th scope="col">Handle</th>
        </tr>
        </thead>

        <tbody>
        {% for patient in patient_list %}
            <tr>
                <th scope="row">{{ patient.id }}</th>
                <td>{{ patient.first_name }}</td>
                <td>{{ patient.last_name }}</td>
                <td>{{ patient.age }}</td>
                <td><a href="{% url 'patients:update' patient.pk %}">Update</a>
                    <a href="{% url 'patients:delete' patient.pk %}">Delete</a>
                    <a href="{% url 'patients:add_data' patient.pk %}">Add data</a>
                    <a href="{% url 'patients:analyze' patient.pk %}">Analyze</a>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <a href="{% url 'patients:create' %}" class="btn btn-success" type="button">create</a>

{% endblock %}